### ISSUE TITLE
Examples for testing

### ISSUE THREAD

**Issue by sdruskat** [TraCES-Lexicon/lexicon#35]
I'm starting to implement automated testing for the API and need a number of examples to test against.

Please provide at least three examples per category, with a complete solution, so that I can test that the API works correctly.
"Categories" are, e.g.:
- Forms with/without proclitics
- Nominal forms with/without affixes
- Verbs with/without any combination of prefix/affix/pronoun
- Examples for homophones
- etc.

What I need for each example to be testable is:
- Fidal representation
- Transliteration
- Complete grammatical categorization (including that of pronouns if applicable)
- Root + stem
- Lemma
- Correct pattern

@PietroLiuzzo Could you please assign to those who might be able to provide the examples? Thanks!

**Comment by PietroLiuzzo** [comment]
Aren't the ones in the tables fine? I can extract them from the tables which vitagrazia and magda did, but it sounds a bit cumbersome and you will have to wait that I am back from mekelle...

**Comment by PietroLiuzzo** [comment]
perhaps @AndreasEllwardt, @abausi, @SusanneHummel can provide here some examples as describe above, selecting cases which are simple as well as cases which are complex.

**Comment by sdruskat** [comment]
That'd be great, thanks.

**Comment by MagdaKrzyz** [comment]
Dear Stephan,

I am sending you some examples for your queries. In the field "Complete grammatical categorisation" I gave the annotation according to TraCES. Note that some of the features can be determined only in the context (not in isolated words). That is why, espcially for nouns, it is good to work with a text. If sth is unclear, please write me back.
Best
M
[Stephan_examples.docx](https://github.com/TraCES-Lexicon/lexicon/files/2538427/Stephan_examples.docx)
agda

**Comment by PietroLiuzzo** [comment]
@sdruskat are you happy with this? 
I actually find a bit confusing that the solutions offered in the examples are the TraCES morphological annotations. This was never a requirement for the parser, also because these annotation are contextual, and a parser working on a word only cannot know all what is in there. 
The tables provided do not allow to retrive this information as far as I know. Also the prefixes are hard coded in a table, but how would one know from there the state? 
That is way the demo parser returns searches into the annotations to that end. But Stephan does not have those, or I am missing something? 
Especially the first part on nouns is IMHO impossible to calculate from the data in the tables, it would need to use the TraCES annotations and this would not be logic, but matching in a corpus only which should return contextualized results.

**Comment by abausi** [comment]
I agree with this: the parser has NOT to take into account the TraCES 
annotation; it has exactly to work ignoring all that is there, that is 
the result of a completely different process of analysis - i.e. the 
other way around.

Il 02.11.2018 08:50, Pietro Liuzzo ha scritto:

**Comment by sdruskat** [comment]
Thanks @MagdaKrzyz for the examples. They work well for the representations, lemma, and pattern.

There has been some confusion around the model of the parser vs. TraCES annotations. Just to be clear here, I can only implement what is possible to retrieve from structured information on the word level, not the context, similar to what the demo parser does (including hard-coded information).
